### PR TITLE
Add allocAndCompare() and seekKey()

### PR DESCRIPTION
**Pull request by jerive**

### CODE REVIEW

**Comment by staltz** [comment]
Looks great @jerive ! Can I merge?

**Comment by staltz** [comment]
Well, I guess I can merge. I tested it out, and some tests for `seekKey` and `slice` are passing, which is great. :tada:

**Comment by jerive** [comment]
@staltz by the way is it on purpose that test-compat is git ignored?

**Comment by staltz** [comment]
Yes, because we shouldn't edit those files manually, they are automatically downloaded from `bipf` from npm.

**Pull request merged**
